name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
          
      - name: Navigate to Backend
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: echo "Navigated to backend directory"

      - name: Install Dependencies
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: npm install

      - name: Run Tests
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: npx jest --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./project phase 2/BashCoffee-CompanyA-backend/coverage/lcov.info

  robot-framework-tests:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Run Robot Framework Tests
        run: |
          robot --output output.xml --log log.html --report report.html "./project phase 2/automated test cases"

      - name: Upload Robot Framework Reports
        uses: actions/upload-artifact@v3
        with:
          name: robot-reports
          path: |
            ./project phase 2/automated test cases/output.xml
            ./project phase 2/automated test cases/log.html
            ./project phase 2/automated test cases/report.html
