name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
          
      - name: Navigate to Backend
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: echo "Navigated to backend directory"

      - name: Install Dependencies
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: npm install

      - name: Run Tests
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: npx jest --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./project phase 2/BashCoffee-CompanyA-backend/coverage/lcov.info

  robot-tests:
      name: Run Robot Framework UI Tests
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./project phase 2/
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y xvfb fluxbox wget unzip
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
            CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*})
            wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip -d /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
            python -m pip install --upgrade pip
            pip install robotframework robotframework-seleniumlibrary
      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          fluxbox &

      - name: Verify ChromeDriver Version
        run: chromedriver --version
    
      - name: Verify Google Chrome Version
        run: google-chrome --version
    
      - name: Run Robot Framework tests
        run: |
          cd "automated test cases"
          robot --outputdir results TestAddCart_1.robot TestAddCart_2.robot TestAddCart_3.robot TestFilterBakery.robot TestFilterCoffee.robot TestFilterMatcha.robot TestSearch_1.robot TestSearch_2.robot TestSearch_3.robot
