name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
          
      - name: Navigate to Backend
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: echo "Navigated to backend directory"

      - name: Install Dependencies
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: npm install

      - name: Run Tests
        working-directory: "./project phase 2/BashCoffee-CompanyA-backend"
        run: npx jest --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./project phase 2/BashCoffee-CompanyA-backend/coverage/lcov.info

  robot-ui-tests:
    name: Run Robot Framework UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome and WebDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Dependencies
        run: |
          sudo apt-get install -y xvfb fluxbox
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary

      - name: Start Xvfb and Fluxbox
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          fluxbox &

      - name: Run Robot Framework Tests
        run: |
          cd "project phase 2/automated test cases"
          robot -d results TestAddCart_1.robot TestAddCart_2.robot TestAddCart_3.robot TestFilterBakery.robot TestFilterCoffee.robot TestFilterMatcha.robot TestSearch_1.robot TestSearch_2.robot TestSearch_3.robot

      - name: Upload Robot Framework Test Results
        uses: actions/upload-artifact@v3
        with:
          name: robot-test-results
          path: "project phase 2/automated test cases/results"
