name: Robot Framework UI Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb fluxbox
        pip install robotframework robotframework-seleniumlibrary

    - name: Run Robot Framework tests
      run: |
        xvfb-run robot "./project phase 2/automated test cases/TestAddCart_1.robot"
        xvfb-run robot "./project phase 2/automated test cases/TestAddCart_2.robot"
        xvfb-run robot "./project phase 2/automated test cases/TestAddCart_3.robot"
        xvfb-run robot "./project phase 2/automated test cases/TestFilterBakery.robot"
        xvfb-run robot "./project phase 2/automated test cases/TestFilterCoffee.robot"
        xvfb-run robot "./project phase 2/automated test cases/TestFilterMatcha.robot"
        xvfb-run robot "./project phase 2/automated test cases/TestSearch_1.robot"
        xvfb-run robot "./project phase 2/automated test cases/TestSearch_2.robot"
        xvfb-run robot "./project phase 2/automated test cases/TestSearch_3.robot"

    - name: Upload Robot Framework Reports
      uses: actions/upload-artifact@v3
      with:
        name: robot-reports
        path: |
          "./project phase 2/automated test cases/output.xml"
          "./project phase 2/automated test cases/log.html"
          "./project phase 2/automated test cases/report.html"
